// Code generated by "stringer -type UTC"; DO NOT EDIT.

package time

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UTC_12 - -12]
	_ = x[UTC_11 - -11]
	_ = x[UTC_10 - -10]
	_ = x[UTC_9 - -9]
	_ = x[UTC_8 - -8]
	_ = x[UTC_7 - -7]
	_ = x[UTC_6 - -6]
	_ = x[UTC_5 - -5]
	_ = x[UTC_4 - -4]
	_ = x[UTC_3 - -3]
	_ = x[UTC_2 - -2]
	_ = x[UTC_1 - -1]
	_ = x[UTC0-0]
	_ = x[UTC1-1]
	_ = x[UTC2-2]
	_ = x[UTC3-3]
	_ = x[UTC4-4]
	_ = x[UTC5-5]
	_ = x[UTC6-6]
	_ = x[UTC7-7]
	_ = x[UTC8-8]
	_ = x[UTC9-9]
	_ = x[UTC10-10]
	_ = x[UTC11-11]
	_ = x[UTC12-12]
}

const _UTC_name = "UTC_12UTC_11UTC_10UTC_9UTC_8UTC_7UTC_6UTC_5UTC_4UTC_3UTC_2UTC_1UTC0UTC1UTC2UTC3UTC4UTC5UTC6UTC7UTC8UTC9UTC10UTC11UTC12"

var _UTC_index = [...]uint8{0, 6, 12, 18, 23, 28, 33, 38, 43, 48, 53, 58, 63, 67, 71, 75, 79, 83, 87, 91, 95, 99, 103, 108, 113, 118}

func (i UTC) String() string {
	i -= -12
	if i < 0 || i >= UTC(len(_UTC_index)-1) {
		return "UTC(" + strconv.FormatInt(int64(i+-12), 10) + ")"
	}
	return _UTC_name[_UTC_index[i]:_UTC_index[i+1]]
}
